Hometask 1
SergeyMalyshevsky/smart-home-2020 pull request #1
Opened 2020-09-28 16:23 UTC by SergeyMalyshevsky

Refactore with SOLID principles

2020-10-05 14:06 UTC, a-ivanov requested changes

2020-10-05 14:06 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          while (event != null) {
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D0%BF%D0%B5%D1%80%D0%B5%D0%BD%D0%B5%D1%81%D0%B8%D1%82%D0%B5-%D0%BB%D0%BE%D0%B3%D0%B8%D0%BA%D1%83-%D1%86%D0%B8%D0%BA%D0%BB%D0%B0-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9-%D0%B2-%D0%BE%D1%82%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%BA%D0%BB%D0%B0%D1%81%D1%81

2020-10-05 14:06 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
> +    public static void saveConfiguration(Collection<Room> roomArrays, String filepath) throws IOException {
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D0%BD%D0%B5-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D1%83%D0%B9%D1%82%D0%B5-%D1%81%D1%82%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B-%D0%B2-%D0%B1%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%BB%D0%BE%D0%B3%D0%B8%D0%BA%D0%B5

2020-10-05 14:06 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
> +    public static void saveConfiguration(Collection<Room> roomArrays, String filepath) throws IOException {
Здесь нужна абстракция (интерфейс) для чтения состояния дома и реализация для чтения из json.

2020-10-05 14:06 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public void processEvent(SensorEvent event) {
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D0%B4%D0%B5%D0%BB%D0%B5%D0%B3%D0%B8%D1%80%D1%83%D0%B9%D1%82%D0%B5-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D1%83-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9-%D0%BE%D1%82%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%BC-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0%D0%BC

2020-10-05 14:06 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public void processEvent(SensorEvent event) {
Нарушение SRP. Дом только содержит информацию о состоянии дома.

2020-10-05 14:06 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +        for (Room room : this.getRooms()) {
Это ответственность отдельных обработчиков.

2020-10-07 07:22 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          while (event != null) {
Создал новый класс для загрузки и сохранения конфигураций умного дома

2020-10-07 07:22 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
> +    public static void saveConfiguration(Collection<Room> roomArrays, String filepath) throws IOException {
Перенес чтение состояния дома в отдельный класс

2020-10-07 07:23 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public void processEvent(SensorEvent event) {
Перенес функционал обработки событий в класс EventManager

2020-10-07 21:19 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +        for (Room room : this.getRooms()) {
Перенес функционал обработки событий в класс EventManager и удалил дополнительные функции в hometask-2

2020-10-12 22:09 UTC, a-ivanov requested changes

2020-10-12 22:09 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventManager.java
> +    public static SensorEvent getNextSensorEvent() {
Отдельная responsibility, нарушение SRP.

2020-10-12 22:09 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventManager.java
> +    public void processEvent(SensorEvent event) {
Отдельная responsibility, нарушение SRP, это ответственность обработчика.

2020-10-12 22:09 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventManager.java
> +    private void executeDoorEvent(SensorEvent event) {
Отдельная responsibility, нарушение SRP, это ответственность обработчика.

2020-10-12 22:09 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventManager.java
> +    private void executeLightEvent(SensorEvent event) {
Отдельная responsibility, нарушение SRP, это ответственность обработчика.

2020-10-12 22:09 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventManager.java
> +    private static void sendCommand(SensorCommand command) {
Отдельная responsibility, нарушение SRP.

2020-10-12 22:09 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventManager.java
> +    private void lightOffAllRooms() {
Отдельная responsibility, это можно оставить внутри обработчика сценариев.

2020-10-12 22:09 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SensorEvent.java
> +    public boolean isLightType() {
Сильно связан с SensorEventType, перенсите методы проверки в соответсвующие обработчики

2020-10-12 22:09 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeReaderWriter.java
> +    SmartHome loadSmartHome() throws RuntimeException, IOException;
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D0%BD%D0%B5-%D0%B4%D0%B0%D0%B2%D0%B0%D0%B9%D1%82%D0%B5-%D0%B0%D0%B1%D1%81%D1%82%D1%80%D0%B0%D0%BA%D1%86%D0%B8%D0%B8-%D1%82%D0%B5%D1%87%D1%8C

2020-10-12 22:09 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeReaderWriter.java
> +public interface SmartHomeReaderWriter {
Я бы сказал, что тут нарушается ISP, разделите на два интерфейса. Не всегда нужно читать и писать данные (судя по вашей логике в main/Application.run).

2020-11-04 13:28 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/EventManager.java
> +    public static SensorEvent getNextSensorEvent() {
Создал класс RandomSensorEventsSender и перенес метод в него

2020-11-04 13:32 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/EventManager.java
> +    public void processEvent(SensorEvent event) {
Создал интерфейс IEventHandler и классы DoorEventHandler, HallDoorEventHandler и LightEventHandler, реализующие его

2020-11-04 13:32 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/EventManager.java
> +    private void executeDoorEvent(SensorEvent event) {
Перенес функционал в класс DoorEventHandler

2020-11-04 13:33 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/EventManager.java
> +    private void executeLightEvent(SensorEvent event) {
Перенес функционал в класс LightEventHandler

2020-11-04 13:34 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/EventManager.java
> +    private static void sendCommand(SensorCommand command) {
Перенес метод в класс CommandSender

2020-11-04 13:34 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/EventManager.java
> +    private void lightOffAllRooms() {
Перенес в класс HallDoorEventHandler

2020-11-04 13:36 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/SmartHomeReaderWriter.java
> +    SmartHome loadSmartHome() throws RuntimeException, IOException;
Разделил на два интерфейса ISmartHomeLoader и ISmartHomeSaver

2020-11-04 13:36 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/SmartHomeReaderWriter.java
> +public interface SmartHomeReaderWriter {
Разделил на два интерфейса ISmartHomeLoader и ISmartHomeSaver

2020-11-04 13:41 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/SensorEvent.java
> +    public boolean isLightType() {
Удалил метод из-за ненужности в последней реализации

2020-11-09 08:34 UTC, a-ivanov approved these changes

2020-11-09 08:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/manager/IEventManager.java
> +public interface IEventManager {
В Java конвенции не надо добавлять "I" к названиям интерфейсов, т.е. `IEventManager -> EventManager`.
Для названия класса имплементации интерфейса можно использовать постфикс "Impl", т.е. `EventManager -> EventManagerImpl`.

2020-11-09 08:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/manager/IEventManager.java
> +    void setSmartHome(SmartHome smartHome);
Не обязательно выносить сеттер в API, это деталь реализации.
`SmartHome` можно передать в конструктор в имплементации.

2020-11-09 08:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/handlers/HallDoorEventHandler.java
> +                ICommandSender commandSender = new CommandSender();
Не надо каждый раз заново создавать `CommandSender`. Передайте его через конструктор в поле.

2020-11-09 08:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        while (true) {
Это лучше перенести в `IEventManager`.

2020-11-09 08:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/config/loaders/ISmartHomeLoader.java
> +    SmartHome load() throws RuntimeException, IOException;
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#не-давайте-абстракции-течь

2020-11-24 15:57 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/events/manager/IEventManager.java
> +public interface IEventManager {
Изменил названия интерфейсов

2020-11-24 16:02 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/events/handlers/HallDoorEventHandler.java
> +                ICommandSender commandSender = new CommandSender();
Убрал создание CommandSender из цикла

2020-11-24 16:14 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/events/manager/IEventManager.java
> +    void setSmartHome(SmartHome smartHome);
Убрал метод. Добавил передачу smartHome через конструктор

2020-11-24 16:22 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        while (true) {
Убрал цикл внутрь метода EventManage

2020-11-24 16:28 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/config/loaders/ISmartHomeLoader.java
> +    SmartHome load() throws RuntimeException, IOException;
Убрал RuntimeException из интерфейса

2020-11-24 16:29 UTC, merged