Hometask 2
SergeyMalyshevsky/smart-home-2020 pull request #2
Opened 2020-10-07 07:20 UTC by SergeyMalyshevsky

2020-10-12 22:13 UTC, a-ivanov requested changes

2020-10-12 22:13 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Room.java
> +    public Collection<HomeComponent> getComponents() {
Этого метода не должно по 2 дз, перечитайте задание https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-2

2020-10-12 22:13 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Room.java
> +    public Collection<HomeComponent> getComponents() {
Только execute

2020-10-12 22:13 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Room.java
> +public class Room implements Actionable {
А если я хочу выолпнить действие над комнатой/домом?

2020-11-04 17:21 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/Room.java
> +    public Collection<HomeComponent> getComponents() {
Удалил

2020-11-04 17:22 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/Room.java
> +public class Room implements Actionable {
Добавил реализацию интерфейса Actionable для SmartHome и Room

2020-11-09 08:45 UTC, a-ivanov approved these changes

2020-11-09 08:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/components/Room.java
> +        doors.forEach(door -> door.execute(action));
И еще добавить `action.act(this)`.

2020-11-09 08:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/components/SmartHome.java
> +    }
Еще выполнять действие над самим собой.

2020-11-09 08:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/actions/HallDoorCloseAction.java
> +                    ICommandSender commandSender = new CommandSender();
`ICommandSender` - не надо кго каждый раз создавать заново, передайте в поле через констуктор.

2020-11-09 08:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/handlers/HallDoorEventHandler.java
> +        smartHome.execute(actionable -> {
Можно перенести часть с проверкой двери в холле в отдельную имплементацию Action.

2020-11-24 16:54 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/components/Room.java
> +        doors.forEach(door -> door.execute(action));
Добавил

2020-11-24 16:56 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/components/SmartHome.java
> +    }
Добавил

2020-11-24 17:01 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/actions/HallDoorCloseAction.java
> +                    ICommandSender commandSender = new CommandSender();
Добавил commandSender в конструктор

2020-11-24 17:08 UTC, merged