Hometask 3
SergeyMalyshevsky/smart-home-2020 pull request #3
Opened 2020-10-13 20:45 UTC by SergeyMalyshevsky

2020-10-22 09:55 UTC, a-ivanov requested changes
Нет декоратора из 3 задания.
Также тут должны быть отражены исправления по 1 и 2 дз (исправлены в соответствующих ветках, вмерджены в эту ветку).

2020-10-22 09:55 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/signaling/Signaling.java
> +public class Signaling implements SignalingState{
Сигналищация - не состояние. Она делегирует состояниям для выполнения действий над ней.

2020-10-22 09:55 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/signaling/Signaling.java
> +        SignalingState activateState = new SignalingActivateState();
Смена состояний может быть тут, но должна быть делегация выполнению действия состоянию.
Лучше перенести смену состояния в логику состояний.

2020-10-22 09:55 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/signaling/SignalingAlarmState.java
> +
Должна писать в консоль предупреждение

2020-10-22 09:55 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/signaling/SignalingActivateState.java
> +
Где логика проверки кода?

2020-10-22 09:55 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/signaling/SignalingDeactivateState.java
> +
Где логика активации с установкой кода?

2020-11-04 18:53 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/signaling/Signaling.java
> +public class Signaling implements SignalingState{
Удалил в Signaling имплементацию SignalingState

2020-11-04 18:54 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/signaling/Signaling.java
> +        SignalingState activateState = new SignalingActivateState();
Перенес смену состояний в логику состояний

2020-11-04 18:54 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/signaling/SignalingAlarmState.java
> +
Добавил в метод выдачу предупреждения в консоль

2020-11-04 18:55 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/signaling/SignalingActivateState.java
> +
Добавил логику проверки кода

2020-11-04 18:55 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/signaling/SignalingDeactivateState.java
> +
Добавил логику с установкой кода

2020-11-04 21:44 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/signaling/Signaling.java
> +public class Signaling implements SignalingState{
Добавил декоратор. Смерджил исправления из 1 и 2 дз в текущую ветку

2020-11-09 08:52 UTC, a-ivanov approved these changes

2020-11-09 08:52 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/manager/SignalingEventManager.java
> +    private void processSignalingEvent(SensorEvent event) {
Это скорее логика отдельного обработчика. В `SignalingEventManager` можно только оставить проверку сигнализации и делегацию `IEventManager`.

2020-11-09 08:52 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/manager/SignalingEventManager.java
> +            System.out.println("Sending sms");
Лучше выделить логику отправки смс в отдельный интерфейс `Notifier` с имплементацией `DummySmsSender implements Notifier`.

2020-11-24 17:48 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/events/manager/SignalingEventManager.java
> +            System.out.println("Sending sms");
Добавил класс для отправки смс

2020-11-24 17:48 UTC, merged