Hometask 4
SergeyMalyshevsky/smart-home-2020 pull request #4
Opened 2020-10-28 14:39 UTC by SergeyMalyshevsky

2020-11-09 08:55 UTC, a-ivanov requested changes
Нет конфигурации и адаптера по 4 заданию.

2020-11-28 11:57 UTC, a-ivanov requested changes

2020-11-28 11:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/adapters/EventTypeMapper.java
> +        map.put("LightIsOn", LIGHT_ON);
Вынесите мапу в аргумент конструктора, здесь хардкодить не надо, она может меняться

2020-11-28 11:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/adapters/CCSensorEventToSensorEventMapper.java
> +        this.map = mapper.getMap();
Зачем? Вам же здесь нужна сама мапа, тогда mapper - лишний. Просто сделайте здесь аргумент - мапу, mapper вообще удалите как класс. Саму мапу можно настроить в бине в конфигурации.

2020-11-28 11:58 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/adapters/EventTypeMapper.java
> +        map.put("LightIsOn", LIGHT_ON);
В итоге этот класс вообще лучше удалить и заменить его мапой.

2020-11-30 15:10 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/events/adapters/EventTypeMapper.java
> +        map.put("LightIsOn", LIGHT_ON);
Удалил класс EventTypeMapper

2020-11-30 15:11 UTC, SergeyMalyshevsky commented on src/main/java/ru/sbt/mipt/oop/events/adapters/CCSensorEventToSensorEventMapper.java
> +        this.map = mapper.getMap();
Вместо класса EventTypeMapper в качестве аргумента передаем Map<String, SensorEventType>

2020-12-01 08:19 UTC, a-ivanov approved these changes

2020-12-01 14:51 UTC, merged